cyberflux:
  engine:
    gateway:
      enable: true
      uri: http://127.0.0.1:18087/api/gateway/register
      retry-interval: 60s
      max-retries: 3
    cluster:
      enable: true
      port: 10004
      mode: node
      name: ${spring.application.name}
      nodes: 127.0.0.1:10001,127.0.0.1:10002,,127.0.0.1:10003
    reactor:
      mqtt-options: [
        {type: tcp, port: 1886}
      ]
server:
  port: 20003
spring:
  application:
    name: node-3