/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./../../src/components/common/src/Banner.vue')['default']
    Dashboard: typeof import('./../../src/components/icons/src/Dashboard.vue')['default']
    DataIntegration: typeof import('./../../src/components/icons/src/DataIntegration.vue')['default']
    Device: typeof import('./../../src/components/icons/src/Device.vue')['default']
    DissolvedOxygen: typeof import('./../../src/components/icons/src/DissolvedOxygen.vue')['default']
    HexMesh: typeof import('./../../src/components/common/src/HexMesh.vue')['default']
    LogoNaiveUi: typeof import('./../../src/components/icons/src/LogoNaiveUi.vue')['default']
    LogoNaiveUI: typeof import('./../../src/components/icons/src/LogoNaiveUI.vue')['default']
    LogoNodejs: typeof import('./../../src/components/icons/src/LogoNodejs.vue')['default']
    LogoVue: typeof import('./../../src/components/icons/src/LogoVue.vue')['default']
    NaiveContainer: typeof import('./../../src/components/container/src/NaiveContainer.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialog: typeof import('naive-ui')['NDialog']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    PotentialHydrogen: typeof import('./../../src/components/icons/src/PotentialHydrogen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityAccess: typeof import('./../../src/components/icons/src/SecurityAccess.vue')['default']
    SystemSetting: typeof import('./../../src/components/icons/src/SystemSetting.vue')['default']
    Thermometer: typeof import('./../../src/components/icons/src/Thermometer.vue')['default']
    TimeAgo: typeof import('./../../src/components/common/src/TimeAgo.vue')['default']
    Turbidity: typeof import('./../../src/components/icons/src/Turbidity.vue')['default']
  }
}
