/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./../../src/components/common/src/Banner.vue')['default']
    Dashboard: typeof import('./../../src/components/icons/src/Dashboard.vue')['default']
    DataIntegration: typeof import('./../../src/components/icons/src/DataIntegration.vue')['default']
    Device: typeof import('./../../src/components/icons/src/Device.vue')['default']
    DissolvedOxygen: typeof import('./../../src/components/icons/src/DissolvedOxygen.vue')['default']
    HexMesh: typeof import('./../../src/components/common/src/HexMesh.vue')['default']
    NaiveContainer: typeof import('./../../src/components/container/src/NaiveContainer.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PotentialHydrogen: typeof import('./../../src/components/icons/src/PotentialHydrogen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityAccess: typeof import('./../../src/components/icons/src/SecurityAccess.vue')['default']
    SystemSetting: typeof import('./../../src/components/icons/src/SystemSetting.vue')['default']
    Thermometer: typeof import('./../../src/components/icons/src/Thermometer.vue')['default']
    TimeAgo: typeof import('./../../src/components/common/src/TimeAgo.vue')['default']
    Turbidity: typeof import('./../../src/components/icons/src/Turbidity.vue')['default']
  }
}
