server:
    port: 18087
spring:
    application:
        name: cyberflux-cloud
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    r2dbc:
        url: r2dbcs:mysql://43.136.133.43:3306/cyberlite?characterEncoding=UTF-8&serverTimezone=UTC
        username: ming
        password: PLHsabR8N73CBE85
        name: r2dbc
        pool:
            enabled: true
            validation-query: SELECT 1