server:
  port: 20001
cyberflux:
  node-engine:
    cloud:
      enable: true
      uri: http://127.0.0.1:18087/node/register
      retry-interval: 10s
      max-retries: 3
    cluster:
      enable: true
      port: 10001
      name: node-1
      namespace: default
      nodes: 127.0.0.1:10002,127.0.0.1:10003