cyberflux:
  node-engine:
    cloud:
      enable: true
      uri: http://127.0.0.1:18087/node/register
      retry-interval: 10s
      max-retries: 3
    cluster:
      enable: true
      port: 10001
      name: node-1
      namespace: default
      nodes: 127.0.0.1:10002,127.0.0.1:10003

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: localhost
    #服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效时间
    lease-expiration-duration-in-seconds: 60

  client:
    register-with-eureka: true # 表示是否向Eureka注册中心注册自己
    fetch-registry: true # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://127.0.0.1:18087/eureka

server:
  port: 20001

spring:
  application:
    name: node-1