/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./../../src/components/common/src/Banner.vue')['default']
    Cluster: typeof import('./../../src/components/icons/src/Cluster.vue')['default']
    Cpu: typeof import('./../../src/components/icons/src/Cpu.vue')['default']
    CPU: typeof import('@/components/icons/src/Cpu.vue')['default']
    Dashboard: typeof import('./../../src/components/icons/src/Dashboard.vue')['default']
    DataIntegration: typeof import('./../../src/components/icons/src/DataIntegration.vue')['default']
    Device: typeof import('./../../src/components/icons/src/Device.vue')['default']
    HexMesh: typeof import('./../../src/components/common/src/HexMesh.vue')['default']
    Jvm: typeof import('@/components/icons/src/LogoJava.vue')['default']
    LogoJava: typeof import('./../../src/components/icons/src/LogoJava.vue')['default']
    LogoNaiveUi: typeof import('./../../src/components/icons/src/LogoNaiveUi.vue')['default']
    LogoNodejs: typeof import('./../../src/components/icons/src/LogoNodejs.vue')['default']
    LogoVue: typeof import('./../../src/components/icons/src/LogoVue.vue')['default']
    NaiveContainer: typeof import('./../../src/components/container/src/NaiveContainer.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NLog: typeof import('naive-ui')['NLog']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Notification: typeof import('./../../src/components/icons/src/Notification.vue')['default']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityAccess: typeof import('./../../src/components/icons/src/SecurityAccess.vue')['default']
    SystemSetting: typeof import('./../../src/components/icons/src/SystemSetting.vue')['default']
    TimeAgo: typeof import('./../../src/components/common/src/TimeAgo.vue')['default']
  }
}
